//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractModelContainer : DbContext
    {
        public ContractModelContainer()
            : base("name=ContractModelContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContractRegistryForm> ContractRegistryForms { get; set; }
        public virtual DbSet<SubjectObject> SubjectObjects { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<ArchiveMaterial> ArchiveMaterials { get; set; }
        public virtual DbSet<payTime> payTimes { get; set; }
        public virtual DbSet<ReceiveTime> ReceiveTimes { get; set; }
        public virtual DbSet<PreRegisterRecording> PreRegisterRecordings { get; set; }
        public virtual DbSet<FormalRegisterRecording> FormalRegisterRecordings { get; set; }
        public virtual DbSet<PayRecording> PayRecordings { get; set; }
        public virtual DbSet<ReceiveRecording> ReceiveRecordings { get; set; }
    }
}
