//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRegistryForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractRegistryForm()
        {
            this.SubjectObjects = new HashSet<SubjectObject>();
            this.Departments = new HashSet<Department>();
            this.ArchiveMaterials = new HashSet<ArchiveMaterial>();
            this.payTimes = new HashSet<payTime>();
            this.ReceiveTimes = new HashSet<ReceiveTime>();
            this.ReceiveRecordings = new HashSet<ReceiveRecording>();
            this.PayRecordings = new HashSet<PayRecording>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public int FinancialFlow { get; set; }
        public bool IsForeignContract { get; set; }
        public string Description { get; set; }
        public string SubjectObjectOther { get; set; }
        public int FundsType { get; set; }
        public string Operator { get; set; }
        public string ProjectNumber { get; set; }
        public string BudgetNumber { get; set; }
        public double Money { get; set; }
        public int Currency { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string TargetCompanyName { get; set; }
        public string ArchiveMaterialOther { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectObject> SubjectObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchiveMaterial> ArchiveMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payTime> payTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiveTime> ReceiveTimes { get; set; }
        public virtual PreRegisterRecording PreRegisterRecording { get; set; }
        public virtual FormalRegisterRecording FormalRegisterRecording { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiveRecording> ReceiveRecordings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRecording> PayRecordings { get; set; }
    }
}
