//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContractManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class payTime
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public double ExpectedMoney { get; set; }
        public int ExpectedCurrency { get; set; }
        public string PayCondition { get; set; }
        public System.DateTime PayDate { get; set; }
        public string PayCredential { get; set; }
        public double ActualMoney { get; set; }
        public int ActualCurrency { get; set; }
        public int PayType { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsCredentialFiled { get; set; }
        public string Composition { get; set; }
        public int ContractRegistryFormId { get; set; }
    }
}
